---
- name: "PLAY 1 - COLLECT FACTS FOR IOS"
  hosts: "iosxe"
  connection: "ansible.netcommon.network_cli"
  gather_facts: no

  tasks:
    - name: "COLLECT FACT FOR EOS"
      cisco.ios.ios_facts:

    - name: "DEBUG OS VERSION"
      debug:
        var: ansible_net_version

    - name: "DEBUG HOSTNAME"
      debug:
        var: ansible_net_hostname

    - name: "ISSUE SHOW COMMAND"
      cisco.ios.ios_command:
        commands:
          - "show run | inc snmp-server community"
        register: snmp_data

    - name: "DEBUG COMMAND STRING RESPONSE WITH JINJA SHORTHAND SYNTAX"
      debug:
        var: snmp_data.stdout.0

    - name: "DEBUG COMMAND STRING RESPONSE WITH STANDARD PYTHON SYNTAX"
      debug:
        var: snmp_data['stdout'][0]

    - name: "WRITE DATA TO FILE"
      template:
        src: "basic.j2"
        dest: "./commands/snmp/{{ inventory_hostname }}.txt"
