---
inventory:
    plugin: "SimpleInventory"
    options:
        host_file: "inventory/hosts.yaml"
        group-file: "inventory/groups.yaml"

runner:
    plugin: "threaded"
    options:
        num_workers: 20

