# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: main.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'main.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\x0cnetworkstuff\"\x1b\n\rRouterRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"S\n\x06Router\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12+\n\ninterfaces\x18\x03 \x03(\x0b\x32\x17.networkstuff.Interface\",\n\tInterface\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2O\n\rRouterService\x12>\n\tGetRouter\x12\x1b.networkstuff.RouterRequest\x1a\x14.networkstuff.Routerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTERREQUEST']._serialized_start=28
  _globals['_ROUTERREQUEST']._serialized_end=55
  _globals['_ROUTER']._serialized_start=57
  _globals['_ROUTER']._serialized_end=140
  _globals['_INTERFACE']._serialized_start=142
  _globals['_INTERFACE']._serialized_end=186
  _globals['_ROUTERSERVICE']._serialized_start=188
  _globals['_ROUTERSERVICE']._serialized_end=267
# @@protoc_insertion_point(module_scope)
